# Generated by Django 5.2.7 on 2026-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='methode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('carte', 'Carte bancaire'), ('moov_money', 'Moov Money')], max_length=50),
        ),
    ]
