# Generated by Django 5.2.7 on 2026-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_methode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
