# Generated by Django 6.0.7 on 2026-07-25 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vente_creee', '🛒 Vente enregistrée'), ('vente_modifiee', '✏️ Vente modifiée'), ('vente_supprimee', '🗑️ Vente supprimée'), ('connexion', '🔑 Connexion'), ('deconnexion', '🚪 Déconnexion'), ('stock_modifie', '📦 Stock modifié'), ('prix_modifie', '💰 Prix modifié'), ('acces_refuse', '⛔ Accès refusé'), ('autre', '📝 Autre action')], max_length=50, verbose_name='Action')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Alerte critique')], default='info', max_length=20, verbose_name="Niveau d'alerte")),
                ('details', models.TextField(verbose_name="Détails de l'action")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_activites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': 'Journal des activités',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité vendue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('methode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('carte', 'Carte bancaire')], default='especes', max_length=50, verbose_name='Méthode de paiement')),
                ('reference_client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du client')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='products.product', verbose_name='Produit')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
    ]
