# Generated by Django 6.0.7 on 2026-08-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('vente_creee', 'Vente enregistrée'), ('vente_modifiee', 'Vente modifiée'), ('vente_supprimee', 'Vente supprimée'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('stock_modifie', 'Stock modifié'), ('prix_modifie', 'Prix modifié'), ('acces_refuse', 'Accès refusé'), ('autre', 'Autre action')], max_length=50, verbose_name='Action'),
        ),
    ]
