# Generated by Django 5.2.7 on 2026-09-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Gestion Boutique', max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutique/')),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('devise', models.CharField(default='FCFA', max_length=12)),
                ('seuil_stock_faible', models.PositiveIntegerField(default=5)),
                ('message_recu', models.CharField(default='Merci pour votre achat.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
