# Generated by Django 5.2.7 on 2026-09-12 14:26

import dashboard.depense_files
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_boutiquesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('date_depense', models.DateField(default=django.utils.timezone.localdate)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moyen_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('carte', 'Carte / Banque')], max_length=20)),
                ('beneficiaire', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('justificatif', models.FileField(blank=True, max_length=255, storage=dashboard.depense_files.PrivateExpenseStorage(), upload_to=dashboard.depense_files.justificatif_upload_to, validators=[dashboard.depense_files.validate_justificatif])),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='brouillon', editable=False, max_length=12)),
                ('date_validation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='dashboard.categoriedepense')),
                ('cree_par', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_creees', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-id'],
                'indexes': [models.Index(fields=['statut', 'date_depense'], name='depense_statut_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='depense_montant_positif'), models.CheckConstraint(condition=models.Q(models.Q(('date_validation__isnull', True), ('statut', 'brouillon'), ('validee_par__isnull', True)), models.Q(('date_validation__isnull', False), ('statut__in', ['validee', 'annulee']), ('validee_par__isnull', False)), _connector='OR'), name='depense_validation_coherente')],
            },
        ),
    ]
