# Generated by Django 5.2.7 on 2026-09-12 15:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_categoriedepense_depense'),
        ('payments', '0003_payment_date_paiement_payment_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('type_compte', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('banque', 'Banque')], max_length=20)),
                ('devise', models.CharField(default='FCFA', max_length=12)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('actif', models.BooleanField(default=True)),
                ('est_par_defaut', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type_compte', 'nom', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TransfertFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=45, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(max_length=255)),
                ('cle_operation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('compte_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='dashboard.comptefinancier')),
                ('compte_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='dashboard.comptefinancier')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_transfert', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MouvementFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=45, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sens', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('type_mouvement', models.CharField(choices=[('vente', 'Vente'), ('paiement', 'Paiement'), ('depense', 'Dépense'), ('transfert', 'Transfert'), ('ajustement', 'Ajustement'), ('annulation', 'Annulation')], max_length=15)),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_compte_attendu', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('banque', 'Banque')], max_length=20)),
                ('devise', models.CharField(default='FCFA', max_length=12)),
                ('raison_regularisation', models.CharField(blank=True, max_length=255)),
                ('cle_operation', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='dashboard.comptefinancier')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_financiers', to='dashboard.depense')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_financiers', to='payments.payment')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_financiers', to='dashboard.vente')),
                ('transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='dashboard.transfertfinancier')),
            ],
            options={
                'ordering': ['-date_mouvement', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='comptefinancier',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True), ('est_par_defaut', True)), fields=('type_compte',), name='finance_default_active_type'),
        ),
        migrations.AddConstraint(
            model_name='transfertfinancier',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='transfert_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='transfertfinancier',
            constraint=models.CheckConstraint(condition=models.Q(('compte_source', models.F('compte_destination')), _negated=True), name='transfert_comptes_distincts'),
        ),
        migrations.AddIndex(
            model_name='mouvementfinancier',
            index=models.Index(fields=['compte', 'date_mouvement'], name='finance_compte_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='mouvement_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.CheckConstraint(condition=models.Q(('sens__in', ['entree', 'sortie'])), name='mouvement_sens_valide'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.UniqueConstraint(condition=models.Q(('type_mouvement', 'vente')), fields=('vente',), name='mouvement_unique_vente'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.UniqueConstraint(condition=models.Q(('type_mouvement', 'paiement')), fields=('paiement',), name='mouvement_unique_paiement'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.UniqueConstraint(condition=models.Q(('type_mouvement', 'depense')), fields=('depense',), name='mouvement_unique_depense'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.UniqueConstraint(condition=models.Q(('type_mouvement', 'annulation')), fields=('depense',), name='mouvement_unique_annulation'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.UniqueConstraint(condition=models.Q(('type_mouvement', 'transfert')), fields=('transfert', 'sens'), name='mouvement_unique_transfert_sens'),
        ),
        migrations.AddConstraint(
            model_name='mouvementfinancier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('depense__isnull', True), ('paiement__isnull', True), ('sens', 'entree'), ('transfert__isnull', True), ('type_mouvement', 'vente'), ('vente__isnull', False)), models.Q(('depense__isnull', True), ('paiement__isnull', False), ('sens', 'entree'), ('transfert__isnull', True), ('type_mouvement', 'paiement'), ('vente__isnull', True)), models.Q(('depense__isnull', False), ('paiement__isnull', True), ('sens', 'sortie'), ('transfert__isnull', True), ('type_mouvement', 'depense'), ('vente__isnull', True)), models.Q(('depense__isnull', False), ('paiement__isnull', True), ('sens', 'entree'), ('transfert__isnull', True), ('type_mouvement', 'annulation'), ('vente__isnull', True)), models.Q(('compte__isnull', False), ('depense__isnull', True), ('paiement__isnull', True), ('transfert__isnull', False), ('type_mouvement', 'transfert'), ('vente__isnull', True)), models.Q(('compte__isnull', False), ('depense__isnull', True), ('paiement__isnull', True), ('transfert__isnull', True), ('type_mouvement', 'ajustement'), ('vente__isnull', True)), _connector='OR'), name='mouvement_source_coherente'),
        ),
    ]
