# Generated by Django 5.2.7 on 2026-09-12 15:55

import dashboard.cloture_models
import dashboard.depense_files
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('dashboard', '0004_comptefinancier_transfertfinancier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=45, unique=True)),
                ('date_cloture', models.DateField(default=django.utils.timezone.localdate)),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=24)),
                ('solde_constate', models.DecimalField(decimal_places=2, max_digits=24)),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=24)),
                ('solde_initial_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=24)),
                ('total_entrees', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=24)),
                ('total_sorties', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=24)),
                ('nombre_mouvements', models.PositiveIntegerField(default=0, editable=False)),
                ('devise', models.CharField(editable=False, max_length=12)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='brouillon', editable=False, max_length=12)),
                ('commentaire', models.TextField(blank=True)),
                ('justificatif', models.FileField(blank=True, max_length=255, storage=dashboard.depense_files.PrivateExpenseStorage(), upload_to=dashboard.cloture_models.cloture_upload_to, validators=[dashboard.depense_files.validate_justificatif])),
                ('date_validation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to='dashboard.comptefinancier')),
                ('cree_par', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='clotures_creees', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clotures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_cloture', '-pk'],
                'indexes': [models.Index(fields=['date_cloture', 'statut'], name='cloture_date_statut_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'validee')), fields=('compte', 'date_cloture'), name='cloture_unique_validee_compte_date'), models.CheckConstraint(condition=models.Q(models.Q(('date_validation__isnull', True), ('statut', 'brouillon'), ('validee_par__isnull', True)), models.Q(('date_validation__isnull', False), ('statut__in', ['validee', 'annulee']), ('validee_par__isnull', False)), _connector='OR'), name='cloture_validation_coherente'), models.CheckConstraint(condition=models.Q(('ecart', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('solde_constate'), '-', models.F('solde_theorique')), 2))), name='cloture_ecart_coherent')],
            },
        ),
    ]
