# Generated by Django 5.2.7 on 2026-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cloturefinanciere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='methode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('carte', 'Carte bancaire')], default='especes', max_length=50, verbose_name='Méthode de paiement'),
        ),
    ]
