# Generated by Django 5.2.7 on 2026-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_vente_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='afficher_message_recu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='livraison_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='nif',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='pays',
            field=models.CharField(blank=True, default='Mali', max_length=80),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='rccm',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='ville',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
