# Generated by Django 6.0.7 on 2026-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('vendeur', 'Vendeur')], default='client', max_length=20, verbose_name='Rôle'),
        ),
    ]
