# Generated by Django 5.2.7 on 2026-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('vendeur', 'Vendeur'), ('comptable', 'Comptable')], default='client', max_length=20, verbose_name='Rôle'),
        ),
    ]
