# Generated by Django 5.2.7 on 2026-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('non_precise', 'Préfère ne pas préciser')], max_length=20, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu de naissance'),
        ),
    ]
