# Generated by Django 5.2.7 on 2026-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_date_naissance_profile_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('vendeur', 'Vendeur'), ('comptable', 'Comptable'), ('livreur', 'Livreur')], default='client', max_length=20, verbose_name='Rôle'),
        ),
    ]
