# Generated by Django 5.2.7 on 2026-09-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
