"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-change-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default):
    value = os.getenv(name, '')
    values = [item.strip() for item in value.split(',') if item.strip()]
    return values or default


DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    [
        'localhost',
        '127.0.0.1',
        '[::1]',
        '192.168.100.147',
    ],
)

CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
        'http://127.0.0.1',
        'http://localhost',
        'http://192.168.100.147:8000',
        'http://192.168.100.147',
    ],
)

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Applications externes
'crispy_forms',
'crispy_bootstrap5',
'django_filters',

# Applications du projet
'core',
'accounts',
'products',
'categories',
'cart',
'orders',
'payments',
# 'delivery',
'reviews',
'dashboard',
'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications_processor',
                'cart.context_processors.cart_processor',
                'core.context_processors.boutique_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================================
# CONFIGURATION MOOV MONEY (MOOV AFRICA MALI)
# ==========================================================
MOOV_MONEY_API_BASE_URL = os.getenv("MOOV_MONEY_API_BASE_URL", "").strip()
MOOV_MONEY_CLIENT_ID = os.getenv("MOOV_MONEY_CLIENT_ID", "").strip()
MOOV_MONEY_CLIENT_SECRET = os.getenv("MOOV_MONEY_CLIENT_SECRET", "").strip()
MOOV_MONEY_MERCHANT_CODE = os.getenv("MOOV_MONEY_MERCHANT_CODE", "").strip()
MOOV_MONEY_WEBHOOK_SECRET = os.getenv("MOOV_MONEY_WEBHOOK_SECRET", "").strip()
PAYMENT_PROVIDER = os.getenv("PAYMENT_PROVIDER", "").strip().lower()
PAYMENT_PUBLIC_KEY = os.getenv("PAYMENT_PUBLIC_KEY", "").strip()
PAYMENT_SECRET_KEY = os.getenv("PAYMENT_SECRET_KEY", "").strip()
PAYMENT_WEBHOOK_SECRET = os.getenv("PAYMENT_WEBHOOK_SECRET", "").strip()
CINETPAY_API_KEY = os.getenv("CINETPAY_API_KEY", "").strip()
CINETPAY_SITE_ID = os.getenv("CINETPAY_SITE_ID", "").strip()
CINETPAY_SECRET_KEY = os.getenv("CINETPAY_SECRET_KEY", "").strip()


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'
LANGUAGES = [('fr', 'Français'), ('en', 'English')]
LOCALE_PATHS = [BASE_DIR / 'locale']
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_SAMESITE = 'Lax'
# Keep monetary display explicit and stable across languages; calculations remain Decimal.
FORMAT_MODULE_PATH = ['config.formats']

TIME_ZONE = 'Africa/Bamako'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ========================================
# EMAIL CONFIGURATION (Reset Password Flow)
# ========================================
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "",
).strip()

if not EMAIL_BACKEND:
    email_host = os.getenv("EMAIL_HOST", "").strip()
    email_port = os.getenv("EMAIL_PORT", "").strip()
    email_host_user = os.getenv("EMAIL_HOST_USER", "").strip()

    if DEBUG and not email_host:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    elif email_host and email_port and email_host_user:
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


EMAIL_HOST = os.getenv("EMAIL_HOST", "").strip()
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587") or 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Gestion Boutique <noreply@gestionboutique.local>",
).strip()
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if env_bool('DJANGO_SECURE_PROXY_SSL', False)
    else None
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'

# ==========================================
# CONFIGURATION DJANGO UNFOLD (ADMIN PANEL)
# ==========================================
UNFOLD = {
    "SITE_TITLE": "Gestion Boutique Admin",
    "SITE_HEADER": "👑 Gestion Boutique — Administration",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "12px",
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
    },
    "STYLES": ["/static/css/admin.css"],
}
