# Generated by Django 5.2.7 on 2026-08-01 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendeur_confirmateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_confirmees', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur confirmateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
