# Generated by Django 5.2.7 on 2026-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_date_confirmation_order_vendeur_confirmateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresse_livraison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='code_postal_livraison',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_expedition',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_livraison',
            field=models.CharField(default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='ville_livraison',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
