# Generated by Django 5.2.7 on 2026-09-12 16:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_adresse_livraison_order_code_postal_livraison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(blank=True, choices=[('a_affecter', 'À affecter'), ('affectee', 'Affectée'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_route', 'En route'), ('arrive', 'Arrivé'), ('livree', 'Livrée'), ('echec', 'Échec de livraison'), ('annulee', 'Annulée')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('a_affecter', 'À affecter'), ('affectee', 'Affectée'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_route', 'En route'), ('arrive', 'Arrivé'), ('livree', 'Livrée'), ('echec', 'Échec de livraison'), ('annulee', 'Annulée')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LectureLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dernier_message_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(editable=False, max_length=45, unique=True)),
                ('statut', models.CharField(choices=[('a_affecter', 'À affecter'), ('affectee', 'Affectée'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_route', 'En route'), ('arrive', 'Arrivé'), ('livree', 'Livrée'), ('echec', 'Échec de livraison'), ('annulee', 'Annulée')], default='a_affecter', max_length=20)),
                ('date_affectation', models.DateTimeField(blank=True, null=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_prete', models.DateTimeField(blank=True, null=True)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('motif_echec', models.CharField(blank=True, choices=[('client_absent', 'Client absent'), ('adresse_introuvable', 'Adresse introuvable'), ('client_injoignable', 'Client injoignable'), ('refus_client', 'Refus client'), ('autre', 'Autre')], max_length=30)),
                ('commentaire_echec', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MessageLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1000)),
                ('cle_envoi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='numero_porte',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='order',
            name='numero_rue',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='order',
            name='telephone_livraison',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('numero_rue__isnull', True), ('numero_rue__range', (0, 1000)), _connector='OR'), name='order_rue_range'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('numero_porte__isnull', True), ('numero_porte__range', (0, 1000)), _connector='OR'), name='order_porte_range'),
        ),
        migrations.AddField(
            model_name='historiquelivraison',
            name='ancien_livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anciennes_affectations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquelivraison',
            name='nouveau_livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nouvelles_affectations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquelivraison',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_livraison', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturelivraison',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_livraison', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='livraison', to='orders.order'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livraisons_affectees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturelivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='orders.livraison'),
        ),
        migrations.AddField(
            model_name='historiquelivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique', to='orders.livraison'),
        ),
        migrations.AddField(
            model_name='messagelivraison',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_livraison', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagelivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='orders.livraison'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['livreur', 'statut'], name='livraison_livreur_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='livraison',
            constraint=models.CheckConstraint(condition=models.Q(('statut__in', ['a_affecter', 'affectee', 'acceptee', 'en_preparation', 'prete', 'en_route', 'arrive', 'livree', 'echec', 'annulee'])), name='livraison_statut_valide'),
        ),
        migrations.AddConstraint(
            model_name='lecturelivraison',
            constraint=models.UniqueConstraint(fields=('livraison', 'utilisateur'), name='lecture_unique_livraison_user'),
        ),
    ]
