# Generated by Django 5.2.7 on 2026-09-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Information', max_length=160),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('commande', 'Commande'), ('paiement', 'Paiement'), ('livraison', 'Livraison'), ('stock', 'Stock'), ('compte', 'Compte'), ('information', 'Information')], default='information', max_length=20),
        ),
    ]
